/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:423d7148-fcab-473c-979b-d5c84dd9f646",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_qQfjji38K",
    "aws_user_pools_web_client_id": "2kf3f08l1ut203bjck7g3mojb7",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://odrztohqfvdddalzjiz4g7olve.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "aws-athena-query-results-aa-cpshc0j1rjtu-amplify",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
